### ISSUE TITLE
Implement Dark Mode Feature

### ISSUE THREAD

**Issue by snobbee** [snobbee/todo-list#37]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Many users prefer a dark mode for better visibility and reduced eye strain during night time usage.

**Describe the solution you'd like**

Implement a dark mode feature that can be toggled by users. This should include appropriate color schemes for backgrounds, text, and buttons to ensure readability and aesthetic appeal.

**Code Example**

```css
/* Dark mode styles */
body.dark-mode {
    background-color: #121212;
    color: #ffffff;
}
button {
    background-color: #1e1e1e;
    color: #ffffff;
}
```

**Describe alternatives you've considered**

Currently, the application only supports a light mode, which may not cater to all user preferences.

**Additional context**

By incorporating a dark mode, we can enhance user experience and accessibility, making the application more versatile for different environments.

**Related Issues**
- [Issue #35](https://github.com/snobbee/todo-list/issues/35)
- [Issue #36](https://github.com/snobbee/todo-list/issues/36)
